/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cajero.h"

bool_t
xdr_cuenta_args (XDR *xdrs, cuenta_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cuenta))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_movimiento_t (XDR *xdrs, movimiento_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_movimientos_t (XDR *xdrs, movimientos_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->movimientos_t_val, (u_int *) &objp->movimientos_t_len, MOVIMIENTOSC,
		sizeof (movimiento_t), (xdrproc_t) xdr_movimiento_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_historico_t (XDR *xdrs, historico_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_movimientos_t (xdrs, &objp->movs))
		 return FALSE;
	return TRUE;
}
